var cmData = [
    { 'name': 'Isaiah Ian', 'year': '2018', 'coach': 'Ashlee Pitts', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': 'no data', 'retention': 'High', 'alum': 'Unlikely to Stay' },
    { 'name': 'Natalie Cooper', 'year': '2019', 'coach': 'Ashlee Pitts', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.1', 'retention': 'Low', 'alum': 'Will Stay' },
    { 'name': 'Charles Brayden', 'year': '2018', 'coach': 'Ashlee Pitts', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '2', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Aaliyah Samantha', 'year': '2018', 'coach': 'Ashlee Pitts', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Avery Ariana', 'year': '2018', 'coach': 'Ashlee Pitts', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '2', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Quinn Piper', 'year': '2019', 'coach': 'Ashlee Pitts', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.1', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Bryson Cooper', 'year': '2019', 'coach': 'Ashlee Pitts', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.7', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Emilia Jayden', 'year': '2018', 'coach': 'Ashlee Pitts', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.21', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Zoey Quinn', 'year': '2018', 'coach': 'Ashlee Pitts', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.09', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Lucy Madelyn', 'year': '2018', 'coach': 'Ashlee Pitts', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': 'no data', 'retention': 'High', 'alum': 'Unlikely to Stay' },
    { 'name': 'Mateo Owen', 'year': '2018', 'coach': 'Ashlee Pitts', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.8', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Zoe Josephine', 'year': '2019', 'coach': 'Ashlee Pitts', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.2', 'retention': 'None', 'alum': 'Likely to Stay' },
    { 'name': 'Ryan Cora', 'year': '2019', 'coach': 'Ashlee Pitts', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.8', 'retention': 'High', 'alum': 'Unlikely to Stay' },
    { 'name': 'Aaron Mila', 'year': '2019', 'coach': 'Ashlee Pitts', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.4', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Sebastian John', 'year': '2018', 'coach': 'Elaina Ballard', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': 'no data', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Madelyn Violet', 'year': '2018', 'coach': 'Elaina Ballard', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': 'no data', 'retention': 'High', 'alum': 'Unlikely to Stay' },
    { 'name': 'Hannah Lillian', 'year': '2018', 'coach': 'Elaina Ballard', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': 'no data', 'retention': 'Low', 'alum': 'Likely to Stay' },
    { 'name': 'Jack Eliana', 'year': '2018', 'coach': 'Elaina Ballard', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.5', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Ariana Chloe', 'year': '2019', 'coach': 'Elaina Ballard', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.8', 'retention': 'Low', 'alum': 'Likely to Stay' },
    { 'name': 'John Eleanor', 'year': '2019', 'coach': 'Elaina Ballard', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.8', 'retention': 'High', 'alum': 'Unlikely to Stay' },
    { 'name': 'Nova Jaxson', 'year': '2019', 'coach': 'Elaina Ballard', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.8', 'retention': 'Medium', 'alum': 'Wavering' },
    { 'name': 'Julian Lily', 'year': '2019', 'coach': 'Elaina Ballard', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '0', 'retention': 'Medium', 'alum': 'Likely to Stay' },
    { 'name': 'Bella Jace', 'year': '2018', 'coach': 'Elaina Ballard', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.09', 'retention': 'None', 'alum': 'Likely to Stay' },
    { 'name': 'Arianna Daniel', 'year': '2018', 'coach': 'Elaina Ballard', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.07', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Alexander Grayson', 'year': '2018', 'coach': 'Elaina Ballard', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.9', 'retention': 'Low', 'alum': 'Will Stay' },
    { 'name': 'Bryson Vivian', 'year': '2019', 'coach': 'Elaina Ballard', 'specialist': 'Jess Martinson (Elementary)', 'years': '0.72', 'retention': 'Medium', 'alum': 'Likely to Stay' },
    { 'name': 'Chloe Anna', 'year': '2019', 'coach': 'Elaina Ballard', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.27', 'retention': 'Low', 'alum': "<I don't know>" },
    { 'name': 'Jaxon Grace', 'year': '2018', 'coach': 'Elaina Ballard', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '0.9', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Santiago Colton', 'year': '2018', 'coach': 'Elaina Ballard', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': 'no data', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Nova Dominic', 'year': '2018', 'coach': 'Elaina Ballard', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': 'no data', 'retention': 'Medium', 'alum': 'Unlikely to Stay' },
    { 'name': 'Leonardo Evelyn', 'year': '2018', 'coach': 'Elaina Ballard', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': 'no data', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Lily Cameron', 'year': '2019', 'coach': 'Elaina Ballard', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.8', 'retention': 'Low', 'alum': 'Likely to Stay' },
    { 'name': 'Jason Hannah', 'year': '2019', 'coach': 'Elaina Ballard', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': 'no data', 'retention': 'Low', 'alum': 'Likely to Stay' },
    { 'name': 'Emily Skylar', 'year': '2018', 'coach': 'Haley Creed', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '0.8', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Sawyer Jose', 'year': '2018', 'coach': 'Haley Creed', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '0.9', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Zoey Matthew', 'year': '2018', 'coach': 'Haley Creed', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.6', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Mateo Andrew', 'year': '2018', 'coach': 'Haley Creed', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.65', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Liam Sebastian', 'year': '2019', 'coach': 'Haley Creed', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.15', 'retention': 'Low', 'alum': 'Wavering' },
    { 'name': 'Roman Jonathan', 'year': '2019', 'coach': 'Haley Creed', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.6', 'retention': 'Low', 'alum': 'Wavering' },
    { 'name': 'Anna Brielle', 'year': '2018', 'coach': 'Haley Creed', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.7', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Anthony Serenity', 'year': '2018', 'coach': 'Haley Creed', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.05', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Allison Brayden', 'year': '2018', 'coach': 'Haley Creed', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.47', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Eva Parker', 'year': '2019', 'coach': 'Haley Creed', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.2', 'retention': 'None', 'alum': 'Likely to Stay' },
    { 'name': 'Madison Miles', 'year': '2019', 'coach': 'Haley Creed', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.37', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Christopher Everett', 'year': '2019', 'coach': 'Haley Creed', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.1', 'retention': 'High', 'alum': 'Unlikely to Stay' },
    { 'name': 'Madison Chloe', 'year': '2019', 'coach': 'Haley Creed', 'specialist': 'Jess Martinson (Elementary)', 'years': '0.9', 'retention': 'Low', 'alum': 'Likely to Stay' },
    { 'name': 'Ian Brielle', 'year': '2019', 'coach': 'Haley Creed', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.8', 'retention': 'High', 'alum': 'Unlikely to Stay' },
    { 'name': 'Ariana Stella', 'year': '2019', 'coach': 'Haley Creed', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.5', 'retention': 'Low', 'alum': 'Wavering' },
    { 'name': 'Ethan Jack', 'year': '2019', 'coach': 'Haley Creed', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.2', 'retention': 'High', 'alum': "<I don't know>" },
    { 'name': 'Isaac Samantha', 'year': '2019', 'coach': 'Haley Creed', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '0.9', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Ian Aiden', 'year': '2019', 'coach': 'Haley Creed', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.65', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Carter Emery', 'year': '2019', 'coach': 'Haley Creed', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.8', 'retention': 'Medium', 'alum': 'Likely to Stay' },
    { 'name': 'Luna Nathan', 'year': '2019', 'coach': 'Haley Creed', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '0.85', 'retention': 'Low', 'alum': 'Wavering' },
    { 'name': 'Jeremiah Hailey', 'year': '2018', 'coach': 'Kacie Neville', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.5', 'retention': 'Low', 'alum': 'Will Stay' },
    { 'name': 'Sebastian Samuel', 'year': '2018', 'coach': 'Kacie Neville', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.5', 'retention': 'None', 'alum': 'Wavering' },
    { 'name': 'Stella Cameron', 'year': '2019', 'coach': 'Kacie Neville', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.03', 'retention': 'Low', 'alum': 'Wavering' },
    { 'name': 'Madeline Vivian', 'year': '2019', 'coach': 'Kacie Neville', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.2', 'retention': 'Low', 'alum': 'Wavering' },
    { 'name': 'Mia Adeline', 'year': '2018', 'coach': 'Kacie Neville', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '0.94', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Anna Samuel', 'year': '2019', 'coach': 'Kacie Neville', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.14', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Hailey Eva', 'year': '2018', 'coach': 'Kacie Neville', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.27', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Santiago Jaxson', 'year': '2018', 'coach': 'Kacie Neville', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.1', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Nolan Lillian', 'year': '2018', 'coach': 'Kacie Neville', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.29', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Grayson Alice', 'year': '2018', 'coach': 'Kacie Neville', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.77', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Penelope Eli', 'year': '2019', 'coach': 'Kacie Neville', 'specialist': 'Jess Martinson (Elementary)', 'years': '0.8', 'retention': 'Low', 'alum': 'Likely to Stay' },
    { 'name': 'Aaron Savannah', 'year': '2018', 'coach': 'Kacie Neville', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.4', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Michael Leah', 'year': '2018', 'coach': 'Kacie Neville', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.23', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Madison Riley', 'year': '2019', 'coach': 'Kacie Neville', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '0.95', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Noah Chloe', 'year': '2019', 'coach': 'Kacie Neville', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.41', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Liam Miles', 'year': '2019', 'coach': 'Kacie Neville', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '0.85', 'retention': 'Low', 'alum': 'Wavering' },
    { 'name': 'Sophie Chloe', 'year': '2018', 'coach': 'Kelsey Smith', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.65', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Aria Lily', 'year': '2018', 'coach': 'Kelsey Smith', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.65', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Sofia Amelia', 'year': '2019', 'coach': 'Kelsey Smith', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '0.5', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Alice Kennedy', 'year': '2019', 'coach': 'Kelsey Smith', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.4', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Everett Alexander', 'year': '2019', 'coach': 'Kelsey Smith', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.65', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Xavier Dominic', 'year': '2019', 'coach': 'Kelsey Smith', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.53', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Allison Dylan', 'year': '2019', 'coach': 'Kelsey Smith', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.7', 'retention': 'Low', 'alum': "<I don't know>" },
    { 'name': 'Jackson Adam', 'year': '2019', 'coach': 'Kelsey Smith', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.7', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Christian Josephine', 'year': '2018', 'coach': 'Kelsey Smith', 'specialist': 'Jess Martinson (Elementary)', 'years': '0.49', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Kayden Eli', 'year': '2018', 'coach': 'Kelsey Smith', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.5', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Levi Everett', 'year': '2019', 'coach': 'Kelsey Smith', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.8', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Jack Mateo', 'year': '2018', 'coach': 'Kelsey Smith', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.8', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Hazel Xavier', 'year': '2018', 'coach': 'Kelsey Smith', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.38', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Chloe Aiden', 'year': '2018', 'coach': 'Kelsey Smith', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.5', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Addison Jackson', 'year': '2018', 'coach': 'Kelsey Smith', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.65', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Jackson James', 'year': '2019', 'coach': 'Kelsey Smith', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.4', 'retention': 'None', 'alum': 'Highly Likely to Stay' },
    { 'name': 'Anthony Quinn', 'year': '2019', 'coach': 'Kelsey Smith', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.05', 'retention': 'Low', 'alum': "<I don't know>" },
    { 'name': 'Anthony Carter', 'year': '2019', 'coach': 'Kelsey Smith', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.3', 'retention': 'Low', 'alum': "<I don't know>" },
    { 'name': 'Caroline Evelyn', 'year': '2018', 'coach': 'Pheron Russell', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.15', 'retention': 'None', 'alum': 'Wavering' },
    { 'name': 'Axel Sofia', 'year': '2019', 'coach': 'Pheron Russell', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '0.5', 'retention': 'Medium', 'alum': "<I don't know>" },
    { 'name': 'Violet Julian', 'year': '2019', 'coach': 'Pheron Russell', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.2', 'retention': 'Low', 'alum': 'Unlikely to Stay' },
    { 'name': 'Colton Genesis', 'year': '2019', 'coach': 'Pheron Russell', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.2', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Owen Anthony', 'year': '2018', 'coach': 'Pheron Russell', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.2', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Bella Charles', 'year': '2018', 'coach': 'Pheron Russell', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '0.8', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Avery Carson', 'year': '2018', 'coach': 'Pheron Russell', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.05', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Jonathan Sophie', 'year': '2019', 'coach': 'Pheron Russell', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.63', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Gianna Sofia', 'year': '2018', 'coach': 'Pheron Russell', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '0.2', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Emery Nolan', 'year': '2018', 'coach': 'Pheron Russell', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.3', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Samantha Emma', 'year': '2019', 'coach': 'Pheron Russell', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '0.8', 'retention': 'High', 'alum': "<I don't know>" },
    { 'name': 'Jackson Ian', 'year': '2019', 'coach': 'Pheron Russell', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.2', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Gianna Jaxson', 'year': '2019', 'coach': 'Pheron Russell', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '0.83', 'retention': 'Low', 'alum': 'Wavering' },
    { 'name': 'Valentina Olivia', 'year': '2019', 'coach': 'Pheron Russell', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.1', 'retention': 'None', 'alum': 'Wavering' },
    { 'name': 'Oliver Stella', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.52', 'retention': 'None', 'alum': 'Wavering' },
    { 'name': 'Joseph Aiden', 'year': '2019', 'coach': 'Sarah Trimm', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.38', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Cooper Violet', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.49', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Isaiah Jeremiah', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.36', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Leonardo Aria', 'year': '2019', 'coach': 'Sarah Trimm', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.38', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Theodore Asher', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.6', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Alexa Jack', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.25', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Zoe Connor', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.6', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Sophie Avery', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.42', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Isla Eliana', 'year': '2019', 'coach': 'Sarah Trimm', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.39', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Jace Kayden', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.25', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Nova Michael', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.6', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'David Josiah', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.5', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Easton Gabriella', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.65', 'retention': 'None', 'alum': 'Likely to Stay' },
    { 'name': 'Jaxson Quinn', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.38', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Kaylee Oliver', 'year': '2019', 'coach': 'Sarah Trimm', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.4', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Henry Luke', 'year': '2019', 'coach': 'Sarah Trimm', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.4', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Camila Aria', 'year': '2018', 'coach': 'Ashlee Pitts', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': 'no data', 'retention': 'None', 'alum': 'Will Stay' },
    { 'name': 'Layla Theodore', 'year': '2018', 'coach': 'Kelsey Smith', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.9', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Kennedy Hannah', 'year': '2019', 'coach': 'Kacie Neville', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': 'no data', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Dylan Carson', 'year': '2019', 'coach': 'Kacie Neville', 'specialist': 'Erin Hoskins (Science & Fine Arts)', 'years': '1.5', 'retention': 'Low', 'alum': "<I don't know>" },
    { 'name': 'Gabriel Samantha', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.3', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Piper Nicholas', 'year': '2019', 'coach': 'Elaina Ballard', 'specialist': 'Bridget Sisney (Math & Tech)', 'years': '1.8', 'retention': 'Low', 'alum': "<I don't know>" },
    { 'name': 'Joseph Jose', 'year': '2018', 'coach': 'Pheron Russell', 'specialist': 'Jess Martinson (Elementary)', 'years': '0', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Sarah Elias', 'year': '2019', 'coach': 'Stephanie Hay', 'specialist': 'Jess Martinson (Elementary)', 'years': '0.57', 'retention': 'None', 'alum': "<I don't know>" },
    { 'name': 'Samuel Olivia', 'year': '2019', 'coach': 'Kacie Neville', 'specialist': 'Jess Martinson (Elementary)', 'years': '1.8', 'retention': 'Low', 'alum': "<I don't know>" },
    { 'name': 'Easton Aria', 'year': '2018', 'coach': 'Haley Creed', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '0.9', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Jeremiah Willow', 'year': '2018', 'coach': 'Sarah Trimm', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '1.5', 'retention': 'None', 'alum': 'Unlikely to Stay' },
    { 'name': 'Sophie Hudson', 'year': '2018', 'coach': 'Elaina Ballard', 'specialist': 'Lauren Huddleston (Liberal Arts)', 'years': '0.77', 'retention': 'None', 'alum': 'Will Stay' }
];